In [148]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn import neighbors
from sklearn.pipeline import Pipeline


TO TRANSFORM

https://stackoverflow.com/questions/38058774/scikit-learn-how-to-scale-back-the-y-predicted-result


https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler.inverse_transform

In [149]:
iris = datasets.load_iris()
X = iris.data[:, :2]  # we only take the first two features.
y = iris.target
X = pd.DataFrame(X)
X.columns=iris.feature_names[:2]
#y = pd.Series(y)
X.head()


sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1
4                5.0               3.6

In [168]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

y_train = y_train.reshape(1, -1)
y_train
#y_test = y_test.reshape(1, -1)

array([[1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0,
        2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2,
        2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2,
        1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2,
        1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2]])

In [167]:
scaled

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [158]:
scalerX = StandardScaler()
X_train = scalerX.fit_transform(X_train)
X_test = scalerX.transform (X_test)

y_train=scalery.fit_transform(y_train)
y_train = y_train.squeeze()

In [159]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k_range=range(1,15)
scores={}
scores_list = []

In [161]:
for k in k_range:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    unscaled = scalery.inverse_transform(y_pred)
    scores[k]=metrics.accuracy_score(unscaled, y_pred)
    scores_list.append(metrics.accuracy_score(unscaled, y_pred))
    print(metrics.accuracy_score(unscaled, y_pred))
    print()

ValueError: operands could not be broadcast together with shapes (50,) (100,) (50,) 

In [140]:
y_train

array([[1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0,
        2, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2,
        2, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2,
        1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2,
        1, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 2]])

In [112]:


scalerX = StandardScaler().fit(X_train)
scalery = StandardScaler().fit(y_train)

X_train_scaled = scalerX.transform(X_train)
y_train_scaled = scalery.transform(y_train)
X_test_scaled = scalerX.transform(X_test)
#y_test = y_test.flatten()

#y_test_scaled = scalery.transform(y_test)


In [120]:
pd.DataFrame(X_train_scaled).head()

0         1
0 -0.138356 -0.265508
1  2.147526 -0.026312
2 -0.258666 -0.026312
3 -0.860214  1.169672
4  2.267836 -0.504705

In [129]:
from sklearn import neighbors
from sklearn.pipeline import Pipeline

steps = [('scalar', StandardScaler()), ('knn', neighbors.KNeighborsRegressor())]

pipeline=Pipeline(steps)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
knn_scaled = pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
y_pred

array([1.2, 0. , 2. , 1.4, 1.4, 0. , 1.2, 1.6, 1.2, 1.4, 2. , 0. , 0. ,
       0. , 0. , 2. , 1.4, 1.2, 1.4, 1.6, 0. , 1.4, 0. , 1.6, 1.8, 1.8,
       1.4, 1.8, 0. , 0. , 0. , 0. , 1.6, 0. , 0. , 1.6, 2. , 0. , 0. ,
       0. , 1.4, 1.8, 1.6, 0. , 0. , 1.2, 1.6, 1.8, 1.6, 1.8])

In [130]:
knn_scaled

Pipeline(memory=None,
         steps=[('scalar',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('knn',
                 KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                     metric='minkowski', metric_params=None,
                                     n_jobs=None, n_neighbors=5, p=2,
                                     weights='uniform'))],
         verbose=False)

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

y_train = y_train.reshape(1, -1)
y_test = y_test.reshape(1, -1)

scalerX = StandardScaler()
scalery = StandardScaler()

X_train_scaled = scalerX.fit_transform(X_train)
y_train_scaled = scalery.fit_transform(y_train)
X_test_scaled = scalerX.fit_transform(X_test)
y_test = y_test.flatten()

y_test = y_test.flatten()
y_test_scaled = scalery.fit_transform(y_test)


ValueError: Expected 2D array, got 1D array instead:
array=[1. 0. 2. 1. 1. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0. 1. 2. 1. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0. 0. 0. 1. 0. 0. 2. 1. 0. 0. 0. 2. 1. 1. 0. 0. 1. 2. 2.
 1. 2.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
y_new_inverse = scalery.inverse_transform(y_new)
